### ISSUE TITLE
Latest (beta) release not available at PyPI

### ISSUE THREAD

**Issue by bignose-debian** [digitalemagine/py-statistics#5]
The [releases for this repository](https://github.com/digitalemagine/py-statistics/releases) has version “v3.4.0 beta 3”. That version is not available at PyPI so is more difficult to depend on.

Please make each release (now and in the future) made at GitHub also released to PyPI for standard installation.

**Comment by stefanocrosta** [comment]
sure, I will shortly and remember to keep it updated in the future as well!

**Comment by stefanocrosta** [comment]
Hello bignose-debian, I'm really sorry for the delay; pypi upload method changed since I last used it, and I had to put aside some uninterrupted time to validate I was not messing something up. Please let me know if this is ok! I'll make an habit of uploading straight after a release.

**Comment by bignose-debian** [comment]
On 10-Oct-2017, Stefano Crosta wrote:
> Please let me know if this is ok! I'll make an habit of uploading
> straight after a release.

Thank you. The “3.4.0b3” release is now at PyPI and I can install it
using Pip, by specifying the version.

PyPI still presents version “1.0.3.5” as the “current” (default)
release. I assume you have explicitly chosen to make version “3.4.0b3”
not the current release. Is that because it is a beta release?

-- 
 \           “Value your freedom or you will lose it, teaches history. |
  `\     “Don't bother us with politics,” respond those who don't want |
_o__)                            to learn.” —Richard M. Stallman, 2002 |
Ben Finney <ben@benfinney.id.au>

**Comment by stefanocrosta** [comment]
Mmh, on pypi 3.4 is the default so it might be related to the beta version indeed. I'll look into that. I have been planning to move to 3.5 stable but they remove a couple of functions so I want to double check before doing that.
